### ISSUE TITLE
JCenter 서비스 종료 대응(CameraView, CircularImageView)

### ISSUE THREAD

**Issue by goahno-phc** [doinglab/FoodLensSDK#2]
JCenter 서비스 종료로 인해 mavenCentral 로 빌드 시 다음과 같은 에러가 발생합니다.
Could not find com.otaliastudios:cameraview:2.6.4.
Could not find com.mikhaellopez:circularimageview:3.2.0.
maven central 에 있는 버전으로 변경이 필요합니다.

**Comment by HyunsukLee-Doinglab** [comment]
JCenter read기능은 지속 지원되기 때문에 문제가 없을것으로 예상되며
현재 신규 SDK개발 중으로 해당 버전 릴리즈 이후에는 문제가 없을 것입니다.
