### ISSUE TITLE
android predictMultipleFood 결과값에 keyName 이 없습니다.

### ISSUE THREAD

**Issue by goahno-phc** [doinglab/FoodLensSDK#3]
android predictMultipleFood 결과값에 keyName 이 없습니다.
android sdk 2.2.12 사용 중 입니다.
RawFood keyname 파싱 에러인 것 같습니다.

**Comment by HyunsukLee-Doinglab** [comment]
내부에서 임시로 활용되는 값으로 외부 App에서 사용도지 않습니다.
