### ISSUE TITLE
accessToken 사용불가

### ISSUE THREAD

**Issue by LeeJeongHo** [doinglab/FoodLensSDK#5]
릴리즈노트에는 2.3.2 배포되었다는데, 22년 4월 13일 2.3.1 이 최신입니다.
2.3.1 버전에서는 AccessToken 만으로는 `FoodLens.createNetworkService(getApplicationContext());` 를 사용할 수 없습니다.

2.3.2 배포는 언제되나요? 아니면 appToken, companyToken을 별도로 받아야하나요?

**Comment by HyunsukLee-Doinglab** [comment]
4월 27일날 2.3.2 버전리 릴리즈 되었습니다.
감사합니다.

**Comment by HyunsukLee-Doinglab** [comment]
릴리즈완료
