### ISSUE TITLE
버전관련 문제 문의드립니다.

### ISSUE THREAD

**Issue by wenddyeah** [doinglab/FoodLensSDK#6]
could not compile build file
startup failed:
build file에서 FOODLENS_SDK_VERSION  = 2.3.2에서 자꾸 오류가 떠서 버전관련 문의드립니다

**Comment by HyunsukLee-Doinglab** [comment]
implementation "com.doinglab.foodlens:FoodLens:2.3.2" 로 직접 세팅해보시기 바랍니다.
