### ISSUE TITLE
rawCalories, rawTotalGram 은 언제 사용하는 건가요?

### ISSUE THREAD

**Issue by YoonKyeongho** [doinglab/FoodLensSDK#9]
1. android 에서 request 를 하면 아래와 같이 response 를 전달합니다. 그 중에 rawCalories, rawTotalGram 은 0 으로 전달되고 있습니다. 필요없는 값인지요?

2. carbonhydrate -> carbohydrate 오타 수정이 필요해보입니다.

SDK version : 2.5.3

{"eatType":-1,"foodPositionList":[{"eatAmount":1.0,"foodCandidates":[{"foodId":9856,"foodName":"킨더 초콜릿","manufacturer":"매일유업","nutrition":{"calcium":150.0,"calories":284.0,"carbonhydrate":27.2,"cholesterol":17.5,"customFoodInfo":false,"dietrayfiber":0.0,"fat":17.5,"protein":4.4,"rawCalories":0.0,"rawTotalGram":0.0,"saturatedfat":11.3,"sodium":61.5,"sugar":26.7,"totalgram":50.0,"transfat":0.2,"unit":"4개","vitamina":0.0,"vitaminb":0.0,"vitaminc":0.0,"vitamind":0.0,"vitamine":0.0}},{"foodId":5642,"foodName":"빅파이","manufacturer":"크라운제과","nutrition":{"calcium":0.0,"calories":170.0,"carbonhydrate":23.0,"cholesterol":0.0,"customFoodInfo":false,"dietrayfiber":0.0,"fat":8.0,"protein":2.0,"rawCalories":0.0,"rawTotalGram":0.0,"saturatedfat":5.0,"sodium":80.0,"sugar":13.0,"totalgram":36.0,"transfat":0.0,"unit":"2봉지","vitamina":0.0,"vitaminb":0.0,"vitaminc":0.0,"vitamind":0.0,"vitamine":0.0}},{"foodId":3389,"foodName":"오예스","manufacturer":"해태제과","nutrition":{"calcium":0.0,"calories":150.0,"carbonhydrate":15.0,"cholesterol":15.0,"customFoodInfo":false,"dietrayfiber":0.0,"fat":9.0,"protein":2.0,"rawCalories":0.0,"rawTotalGram":0.0,"saturatedfat":5.0,"sodium":60.0,"sugar":10.0,"totalgram":30.0,"transfat":0.1,"unit":"봉지","vitamina":0.0,"vitaminb":0.0,"vitaminc":0.0,"vitamind":0.0,"vitamine":0.0}},{"foodId":449,"foodName":"선지해장국","manufacturer":"","nutrition":{"calcium":115.24,"calories":108.96,"carbonhydrate":8.53,"cholesterol":0.0,"customFoodInfo":false,"dietrayfiber":2.72,"fat":3.3,"protein":11.94,"rawCalories":0.0,"rawTotalGram":0.0,"saturatedfat":0.06,"sodium":1015.3,"sugar":0.75,"totalgram":191.5,"transfat":0.0,"unit":"뚝배기","vitamina":69.32,"vitaminb":0.18,"vitaminc":18.27,"vitamind":0.0,"vitamine":1.27}},{"foodId":6590,"foodName":"트윅스","manufacturer":"한국마즈","nutrition":{"calcium":0.0,"calories":240.0,"carbonhydrate":31.0,"cholesterol":5.0,"customFoodInfo":false,"dietrayfiber":0.0,"fat":12.0,"protein":2.0,"rawCalories":0.0,"rawTotalGram":0.0,"saturatedfat":7.0,"sodium":80.0,"sugar":24.0,"totalgram":48.5,"transfat":0.0,"unit":"봉","vitamina":0.0,"vitaminb":0.0,"vitaminc":0.0,"vitamind":0.0,"vitamine":0.0}},{"foodId":6591,"foodName":"트윅스 화이트","manufacturer":"한국마즈","nutrition":{"calcium":0.0,"calories":230.0,"carbonhydrate":29.0,"cholesterol":5.0,"customFoodInfo":false,"dietrayfiber":0.0,"fat":12.0,"protein":2.0,"rawCalories":0.0,"rawTotalGram":0.0,"saturatedfat":7.0,"sodium":75.0,"sugar":22.0,"totalgram":46.0,"transfat":0.0,"unit":"개","vitamina":0.0,"vitaminb":0.0,"vitaminc":0.0,"vitamind":0.0,"vitamine":0.0}},{"foodId":6592,"foodName":"트윅스 미니스","manufacturer":"한국마즈","nutrition":{"calcium":0.0,"calories":155.0,"carbonhydrate":20.0,"cholesterol":5.0,"customFoodInfo":false,"dietrayfiber":0.0,"fat":8.0,"protein":1.0,"rawCalories":0.0,"rawTotalGram":0.0,"saturatedfat":6.0,"sodium":60.0,"sugar":15.0,"totalgram":30.0,"transfat":0.0,"unit":"인분(3개)","vitamina":0.0,"vitaminb":0.0,"vitaminc":0.0,"vitamind":0.0,"vitamine":0.0}},{"foodId":6593,"foodName":"트윅스 화이트 미니스","manufacturer":"한국마즈","nutrition":{"calcium":0.0,"calories":100.0,"carbonhydrate":31.0,"cholesterol":0.0,"customFoodInfo":false,"dietrayfiber":0.0,"fat":5.0,"protein":1.0,"rawCalories":0.0,"rawTotalGram":0.0,"saturatedfat":3.0,"sodium":30.0,"sugar":10.0,"totalgram":20.0,"transfat":0.0,"unit":"개","vitamina":0.0,"vitaminb":0.0,"vitaminc":0.0,"vitamind":0.0,"vitamine":0.0}}],"foodImagepath":"/data/user/0/*/files/temp/0.jpg","imagePosition":{"xmax":896,"xmin":78,"ymax":1024,"ymin":1}}],"mealType":"unknown","predictedImagePath":"/data/user/0/*/files/foodlensStore/fullImage.jpg","version":1}

**Comment by HyunsukLee-Doinglab** [comment]
해당값은 SDK내부적으로 사용되는 값으로, 외부에서는 사용되지 않는 값입니다.
